# Dockerfile to create an environment that contains the Nix package manager.

FROM ubuntu

# Enable HTTPS support in wget and set nsswitch.conf to make resolution work within containers
RUN apt update -y \
  && apt install -y openssl wget xz-utils \
  && rm -rf /var/cache/apt/* \
  && echo hosts: dns files > /etc/nsswitch.conf

# New users and groups
RUN groupadd --system --gid 1000 developer \
  && useradd --system --gid developer --uid 1000 --shell /bin/bash --create-home developer \
  && usermod -aG sudo developer \
  && addgroup --system --gid 30000 nixbld \
  && for i in $(seq 1 30); do useradd --system --home-dir /var/empty --shell $(which nologin) -g nixbld -G nixbld --uid $((30000 + i)) nixbld$i ; done

# Nix directory
RUN mkdir -m 0755 /etc/nix \
  && echo 'sandbox = false' > /etc/nix/nix.conf \
  && mkdir -m 0755 /nix \
  && chown -R developer /nix \
  && chown -R developer /etc/nix

# Download Nix and install it into the system.
USER developer
WORKDIR /home/developer
ARG NIX_VERSION=2.3.10
RUN wget https://nixos.org/releases/nix/nix-${NIX_VERSION}/nix-${NIX_VERSION}-$(uname -m)-linux.tar.xz \
  && tar xf nix-${NIX_VERSION}-$(uname -m)-linux.tar.xz \
  && USER=developer sh nix-${NIX_VERSION}-$(uname -m)-linux/install \
  && rm -r nix-${NIX_VERSION}-$(uname -m)-linux* \
  && /nix/var/nix/profiles/per-user/developer/profile/bin/nix-collect-garbage --delete-old \
  && /nix/var/nix/profiles/per-user/developer/profile/bin/nix-store --optimise \
  && /nix/var/nix/profiles/per-user/developer/profile/bin/nix-store --verify --check-contents

ONBUILD ENV \
    ENV=/etc/profile \
    USER=developer \
    PATH=/nix/var/nix/profiles/per-user/developer/profile/bin:/nix/var/nix/profiles/per-user/developer/profile/sbin:/bin:/sbin:/usr/bin:/usr/sbin \
    GIT_SSL_CAINFO=/etc/ssl/certs/ca-certificates.crt \
    NIX_SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt

ENV \
    ENV=/etc/profile \
    USER=developer \
    PATH=/nix/var/nix/profiles/per-user/developer/profile/bin:/nix/var/nix/profiles/per-user/developer/profile/sbin:/bin:/sbin:/usr/bin:/usr/sbin \
    GIT_SSL_CAINFO=/etc/ssl/certs/ca-certificates.crt \
    NIX_SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt \
    NIX_PATH=/nix/var/nix/profiles/per-user/developer/channels
